replicaCount: 1

image:
  repository: agsats.azurecr.io/api-gateway
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector:
  agentpool: agent2

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - api-gateway
        topologyKey: "kubernetes.io/hostname"

tolerations: []

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "dev"
  - name: TZ
    value: "Asia/Seoul" 